T5 550 generator
mathisschiwy/controlroomtraining pull request #6
Opened 2023-06-20 15:46 UTC by mathisschiwy

2023-06-21 06:20 UTC, JessicaWu1 requested changes, later dismissed

2023-06-21 06:20 UTC, JessicaWu1 commented on project_order_dice/tests/test_enter_names.py
> +        mock_input = ["Hannes", "Jessica", "Henning", "Charlie", ""]
Charlie is in the test and it therefore fails because it can not be removed

2023-06-21 06:20 UTC, JessicaWu1 commented on project_order_dice/tests/test_enter_names.py
> +    def test_exclude_enter_names(self):
This test does not seem to run for me, the exception in names.remove() is still thrown, which leads to an error and the test does not continue past that point.

2023-06-21 06:20 UTC, JessicaWu1 commented on project_order_dice/main.py
> +functions.exclude_enter_names(names)
Do we still need to call the exclude_enter_names function if the YAML file is read and used?
Maybe if we toggle the YAML file usage then it would be useful (either use enter names or yaml file?)

2023-06-21 06:20 UTC, JessicaWu1 commented on project_order_dice/functions.py
> +        except:
You are not defining which exception should be catched. This should be a ValueError.

2023-07-04 15:34 UTC, henning requested changes
I'd like to see the readme be finished and the config file renamed, then I want top approve it finally! thanks ;)

2023-07-04 15:34 UTC, henning commented on project_order_dice/Config/away.yaml
> +away:
This list does not only specify who is away, it's also the main input of which team member names we use for the random order. 

Could for example be named just "team members"

2023-07-04 15:34 UTC, henning commented on project_order_dice/Config/away.yaml
> +away:
Also, because this file then is nopt reduced to define away behaviour, it would better be named just "config.yaml" in my opinion. 

Because then we have a file config.yaml in a directory config, without any other config files for now, it would be easier to remove the directory and have the config file in the main directory.

2023-07-04 15:34 UTC, henning commented on project_order_dice/README.md
> +TODO
Here we want to explain the usage before we merge it (e.g. just do ./main.py)

2023-07-04 15:34 UTC, henning commented on project_order_dice/README.md
> +
maybe add python3 as requirement. (some systems and people still have just python2 - lets help them to know with python 2 they cannot run the program)

2023-07-04 15:34 UTC, henning commented on project_order_dice/functions.py
> +    try:
Maybe we could think about to keep the code a bit more on the left (less cascaded if if try blocks) - but I'm not sure if it's useful and possible in the concrete case

2023-07-06 10:09 UTC, henning commented on project_order_dice/functions.py
> +            for names in monday_names:
Regarding my wish to do less stuff in nested blocks indented deeply to the right: 
the "for names in DAYNAME_names" does not need to be repeated for each day, 
If you store the names for the current day in a name-neutral variable (e.g. "today_names", then you need to have the filtering code only once.

2023-07-06 10:12 UTC, henning commented on project_order_dice/functions.py
> +    except TypeError:
Catching exceptions and just passing them is most often not the best practice, and it should at least be commented why one does it if one does it.

Like now, I would like to try to think about a way that we dont even need the try/catch block and avoid the exception happening in first place, but I dont even understand why it is there in the first place.

2023-07-10 13:24 UTC, henning commented on project_order_dice/main.py
> +functions.manuel_exclude(filtered_names)
small typo: it's "manual" with a

2023-07-11 07:12 UTC, mathisschiwy commented on project_order_dice/main.py
> +functions.manuel_exclude(filtered_names)
Improved it

2023-07-11 13:49 UTC, henning commented on project_order_dice/tests/mock.yaml
> +# If a person is away for a longer period of time please put them on is-away: True.
please use the name text fixture for test fixtures ;)

2023-07-11 13:51 UTC, henning approved these changes, later dismissed
Looks good

2023-07-11 13:53 UTC, henning approved these changes
Looks good

2023-07-11 13:54 UTC, merged